version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    networks:
      - caw
    ports:
      - "3000:3000"
    volumes:
      - ./config.yaml:/packages/config.yaml
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    networks:
      - caw
    ports:
      - "3001:3001"
    volumes:
      - ./config.yaml:/app/config.yaml
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
  database:
    image: postgres:latest
    networks:
      - caw
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  cache:
    image: redis:latest
    networks:
      - caw
    ports:
      - "6379:6379"

volumes:
  database:


networks:
  caw:
